FROM node:20 AS builder

WORKDIR /app

COPY server/package*.json ./

RUN npm install --legacy-peer-deps

COPY server/ ./

RUN npm run build

FROM node:20

WORKDIR /app

ENV NODE_ENV=production

COPY server/package*.json ./

RUN npm install --omit=dev --legacy-peer-deps

COPY --from=builder /app/dist ./dist/

COPY server/src/config ./src/config/

EXPOSE 3000

CMD ["node", "dist/app.js"]
