const { servicesStore, alertRulesStore, logsStore } = require('./store')
const { timeSeriesStore } = require('./timeSeriesStore')
const { generateAllTypesLogs, generateSampleAlertRule, SERVICES } = require('./dataGenerator')
const { v4: uuidv4 } = require('uuid')

function initServices() {
  const existingServices = servicesStore.read()
  
  if (existingServices.length > 0) {
    console.log('Services already initialized, skipping...')
    return
  }
  
  const allServices = []
  
  Object.entries(SERVICES).forEach(([type, serviceNames]) => {
    serviceNames.forEach(name => {
      allServices.push({
        id: uuidv4(),
        name,
        type,
        description: `Auto-initialized ${type} service`,
        metadata: {
          autoGenerated: true,
          initializedAt: new Date().toISOString()
        },
        createdAt: Date.now(),
        updatedAt: Date.now()
      })
    })
  })
  
  allServices.forEach(service => servicesStore.append(service))
  
  console.log(`Initialized ${allServices.length} services`)
}

function initAlertRules() {
  const existingRules = alertRulesStore.read()
  
  if (existingRules.length > 0) {
    console.log('Alert rules already initialized, skipping...')
    return
  }
  
  const defaultRules = [
    generateSampleAlertRule(),
    {
      name: 'High Error Count',
      description: 'Alert when error count exceeds 50 in 1 minute',
      condition: 'count_gt',
      level: 'ERROR',
      service: null,
      keyword: null,
      threshold: 50,
      timeWindow: 60000,
      severity: 'HIGH',
      enabled: true
    },
    {
      name: 'User Service Errors',
      description: 'Alert when user-service has more than 10 errors',
      condition: 'count_gt',
      level: 'ERROR',
      service: 'user-service',
      keyword: null,
      threshold: 10,
      timeWindow: 300000,
      severity: 'MEDIUM',
      enabled: true
    },
    {
      name: 'Payment Service Warnings',
      description: 'Alert when payment-service has warnings',
      condition: 'count_gt',
      level: 'WARN',
      service: 'payment-service',
      keyword: null,
      threshold: 5,
      timeWindow: 60000,
      severity: 'MEDIUM',
      enabled: false
    },
    {
      name: 'Database Connection Errors',
      description: 'Alert when database connection errors occur',
      condition: 'count_gt',
      level: 'ERROR',
      service: null,
      keyword: 'database',
      threshold: 3,
      timeWindow: 60000,
      severity: 'CRITICAL',
      enabled: true
    }
  ]
  
  defaultRules.forEach(rule => {
    rule.id = uuidv4()
    rule.createdAt = Date.now()
    rule.updatedAt = Date.now()
    rule.lastEvaluated = null
    rule.lastTriggered = null
    
    alertRulesStore.append(rule)
  })
  
  console.log(`Initialized ${defaultRules.length} alert rules`)
}

function initSampleLogs(countPerType = 100) {
  const existingLogs = logsStore.read()
  
  if (existingLogs.length > 0) {
    console.log(`Logs already exist (${existingLogs.length} logs), skipping initialization...`)
    return
  }
  
  const logs = generateAllTypesLogs(countPerType)
  
  console.log('Writing logs to legacy store...')
  logs.forEach(log => logsStore.append(log))
  
  console.log('Writing logs to time series store...')
  timeSeriesStore.insertBatch(logs)
  
  console.log(`Initialized ${logs.length} sample logs`)
  console.log(`Time series store stats: ${JSON.stringify(timeSeriesStore.getStats())}`)
}

function initAll(options = {}) {
  const {
    initServicesFlag = true,
    initRulesFlag = true,
    initLogsFlag = true,
    logCount = 100
  } = options
  
  console.log('Starting data initialization...')
  console.log('='.repeat(50))
  
  if (initServicesFlag) {
    initServices()
  }
  
  if (initRulesFlag) {
    initAlertRules()
  }
  
  if (initLogsFlag) {
    initSampleLogs(logCount)
  }
  
  console.log('='.repeat(50))
  console.log('Data initialization completed!')
}

module.exports = {
  initServices,
  initAlertRules,
  initSampleLogs,
  initAll
}

if (require.main === module) {
  const logCount = parseInt(process.argv[2]) || 100
  initAll({ logCount })
}
