export { authApi } from './auth';
export { userApi } from './user';
export { courseApi } from './course';
export { batchApi } from './batch';
export { electiveApi } from './elective';
export { gradeApi } from './grade';
export { statisticApi } from './statistic';
export { teacherApi } from './teacher';
export { categoryApi } from './category';
